### PR TITLE
Fix additivity of features

### LINKED ISSUE #17: no_std features are generally non-additive
Looking forward to testing this crate out in a no_std environment soon, and it's great 
that you support it! 

It is usually non-additive to add a no_std feature, but additive to add a std feature,
then make it default the rust docs on features actually have a section on this exact situation.

https://doc.rust-lang.org/cargo/reference/features-examples.html#no_std-support

### PR DESCRIPTION
**Pull request by ratmice**
This changes the `no-std` feature around to be additive,
It has to jump through some hoops because the `compile_error!()` macro continues compilation, potentially leading to a cascade of errors.

Should fix #17 

Edit: I'm not entirely certain that the .github ci changes of just adding `--no-default-features` and whether that behaves correctly without looking at the CI output though

### CODE REVIEW

File: src/math.rs [hunk 1]
```diff
@@ -1,31 +1,45 @@
+#[cfg(not(any(feature = "std", feature = "libm")))]
+compile_error!("either the `std` or `libm` feature is required");
```
Comment (remi-dupre) [inline src/math.rs:2]: Is it a general recommendation to put this on top of every module? Otherwise maybe the one on top of lib.rs is enough?

**Review by remi-dupre — COMMENTED** [review]
Hi and thanks for the pull request, it looks super relevant!

Could you bump the version and update the CHANGELOG.md? Sadly, as we renamed the feature "no-std", I think it means we need to bump to 2.0, but it's just a number after all 🤷  As it's not directly related to the API but only the build system I had a doubt and found this piece of documentation : https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove

PS: I'll test the CI but it always take me a while to figure out what planets must align to trigger it 😅

EDIT : All it takes is a review apparently, regardless of if it's approving 🤷  (plus a manual trigger)

File: src/math.rs (hunk 1 above)
Comment (ratmice) [reply src/math.rs:2]: Oh, I think I added this to `math.rs` hoping that it would cause the compiler to fatally exit, but ended up having to add hacks anyways to keep the cascading errors out.

I think we can remove this one, good catch!

File: src/math.rs [hunk 2]
```diff
@@ -1,31 +1,45 @@
...
-    #[cfg(feature = "no-std")]
+    #[cfg(feature = "libm")]
     #[allow(clippy::approx_constant)]
     {
         3.141_592_653_589_793
     }
+
+    #[cfg(not(any(feature = "libm", feature = "std")))]
+    {
+        core::f64::NAN
```
[the remark this answers is not in the document]
Comment (ratmice) [reply src/math.rs:19]: Yeah, maybe the compiler_error could go here instead, but it does mean we're going to output one compiler error for each of these places... Which is ultimitely what I was trying to avoid since it makes the error which points to the fix, enabling one of the std or libm features more hidden.

That is why I chose to return arbitrary values, because they don't result in errors.

File: src/math.rs (hunk 1 above)
Comment (ratmice) [reply src/math.rs]: In [e76e265](https://github.com/nathan-osman/rust-sunrise/pull/18/commits/e76e2655fd44c36828ddb0a2cd66d81dcb02d1c4) this is now just at the top of lib.rs.

I believe that that change also fixed all the rest of your review comments (ChangeLog, version bump), and should fix the testsuite.

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,5 +1,11 @@
 # Changelog
 
+## 2.0.0
+
+- To make features additive the "no-std" feature has been replaced by
```
[the remark this answers is not in the document]
Comment (ratmice) [reply CHANGELOG.md:5]: Good catch, should be fixed in [9f4bad0](https://github.com/nathan-osman/rust-sunrise/pull/18/commits/9f4bad0f882033b6e14f44ae5d0397abea1909f1)

**Comment by remi-dupre** [comment]
Looks great, thanks for all your work!
